if(isKeyPressed(Keys.w||isKeyPressed(Keys.upArrow))){
  $this.moveY(10);
}
if(isKeyPressed(Keys.a||isKeyPressed(Keys.leftArrow))){
  $this.moveX(-10);
}
if(isKeyPressed(Keys.s||isKeyPressed(Keys.downArrow))){
  $this.moveY(-10);
}
if(isKeyPressed(Keys.d||isKeyPressed(Keys.rightArrow))){
  $this.moveX(10);
}
